alter table GENESIS_EMPLOYEE_FILE_DESCRIPTOR_LINK add constraint FK_GEFDL_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID);
alter table GENESIS_EMPLOYEE_FILE_DESCRIPTOR_LINK add constraint FK_GEFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
