alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_VIK_IMAGE foreign key (VIK_IMAGE_ID) references SYS_FILE(ID);
create index IDX_GENESIS_EMPLOYEE_VIK_IMAGE on GENESIS_EMPLOYEE (VIK_IMAGE_ID);
