alter table GENESIS_PERSONS add constraint FK_GENESIS_PERSONS_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID);
create index IDX_GENESIS_PERSONS_BUILDING on GENESIS_PERSONS (BUILDING_ID);
