alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID);
create index IDX_GENESIS_EMPLOYEE_BUILDING on GENESIS_EMPLOYEE (BUILDING_ID);
