alter table GENESIS_STORAGE_FILES add constraint FK_GENESIS_STORAGE_FILES_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_GENESIS_STORAGE_FILES_FILE on GENESIS_STORAGE_FILES (FILE_ID);
