alter table GENESIS_STORAGE_FILES add constraint FK_GENESIS_STORAGE_FILES_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID);
create index IDX_GENESIS_STORAGE_FILES_EMPLOYEE on GENESIS_STORAGE_FILES (EMPLOYEE_ID);
