alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_VUZ_IMAGE foreign key (VUZ_IMAGE_ID) references SYS_FILE(ID);
create index IDX_GENESIS_EMPLOYEE_VUZ_IMAGE on GENESIS_EMPLOYEE (VUZ_IMAGE_ID);
