alter table GENESIS_BUILDING add constraint FK_GENESIS_BUILDING_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID);
create index IDX_GENESIS_BUILDING_EMPLOYEE on GENESIS_BUILDING (EMPLOYEE_ID);
