alter table GENESIS_EMPLOYEE add column MEDICAL_CHECK_BASE_BEGIN date ;
alter table GENESIS_EMPLOYEE add column MEDICAL_CHECK_BASE_END date ;
alter table GENESIS_EMPLOYEE add column MEDICAL_CHECK_PERIODIC_BEGIN date ;
alter table GENESIS_EMPLOYEE add column MEDICAL_CHECK_PERIODIC_END date ;
