alter table GENESIS_BUILDING add constraint FK_GENESIS_BUILDING_IMAGE_CONTRACT foreign key (IMAGE_CONTRACT_ID) references SYS_FILE(ID);
create index IDX_GENESIS_BUILDING_IMAGE_CONTRACT on GENESIS_BUILDING (IMAGE_CONTRACT_ID);
