alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_POSITION foreign key (POSITION_ID) references GENESIS_POSITION(ID);
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_DIRECTION_WORK foreign key (DIRECTION_WORK_ID) references GENESIS_DIRECTING(ID);
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_PROFESSION foreign key (PROFESSION_ID) references GENESIS_PROFESSIONS(ID);
create index IDX_GENESIS_EMPLOYEE_DIRECTION_WORK on GENESIS_EMPLOYEE (DIRECTION_WORK_ID);
create index IDX_GENESIS_EMPLOYEE_POSITION on GENESIS_EMPLOYEE (POSITION_ID);
create index IDX_GENESIS_EMPLOYEE_IMAGE on GENESIS_EMPLOYEE (IMAGE_ID);
create index IDX_GENESIS_EMPLOYEE_PROFESSION on GENESIS_EMPLOYEE (PROFESSION_ID);
