alter table GENESIS_CELLS_CK add constraint FK_GENESIS_CELLS_CK_DIRECTING_GROUP foreign key (DIRECTING_GROUP_ID) references GENESIS_DIRECTING(ID);
create index IDX_GENESIS_CELLS_CK_DIRECTING_GROUP on GENESIS_CELLS_CK (DIRECTING_GROUP_ID);
