alter table GENESIS_POSITION add constraint FK_GENESIS_POSITION_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID);
create index IDX_GENESIS_POSITION_BUILDING on GENESIS_POSITION (BUILDING_ID);
