alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_CELLS_CK_ENTITY foreign key (CELLS_CK_ENTITY_ID) references GENESIS_CELLS_CK_ENTITY(ID);
create index IDX_GENESIS_EMPLOYEE_CELLS_CK_ENTITY on GENESIS_EMPLOYEE (CELLS_CK_ENTITY_ID);
