alter table GENESIS_CERTIFICATIONS add constraint FK_GENESIS_CERTIFICATIONS_CERT_IMAGE foreign key (CERT_IMAGE_ID) references SYS_FILE(ID);
alter table GENESIS_CERTIFICATIONS add constraint FK_GENESIS_CERTIFICATIONS_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID);
create index IDX_GENESIS_CERTIFICATIONS_CERT_IMAGE on GENESIS_CERTIFICATIONS (CERT_IMAGE_ID);
create index IDX_GENESIS_CERTIFICATIONS_EMPLOYEE on GENESIS_CERTIFICATIONS (EMPLOYEE_ID);
