alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_DEPARTMENT foreign key (DEPARTMENT_ID) references GENESIS_DEPARTMENT(ID);
create index IDX_GENESIS_EMPLOYEE_DEPARTMENT on GENESIS_EMPLOYEE (DEPARTMENT_ID);
