alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_IMAGE_SIGN foreign key (IMAGE_SIGN_ID) references SYS_FILE(ID);
create index IDX_GENESIS_EMPLOYEE_IMAGE_SIGN on GENESIS_EMPLOYEE (IMAGE_SIGN_ID);
