alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_ECO_SAF_IMAGE foreign key (UD_ECO_SAF_IMAGE_ID) references SYS_FILE(ID);
create index IDX_GENESIS_EMPLOYEE_UD_ECO_SAF_IMAGE on GENESIS_EMPLOYEE (UD_ECO_SAF_IMAGE_ID);
