alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_IMAGE_PHOTO foreign key (IMAGE_PHOTO_ID) references SYS_FILE(ID);
create index IDX_GENESIS_EMPLOYEE_IMAGE_PHOTO on GENESIS_EMPLOYEE (IMAGE_PHOTO_ID);
