-- begin GENESIS_PROFESSIONS
create unique index IDX_GENESIS_PROFESSIONS_UK_NAME_PROFESSION on GENESIS_PROFESSIONS (NAME_PROFESSION) where DELETE_TS is null ^
-- end GENESIS_PROFESSIONS
-- begin GENESIS_POSITION
create unique index IDX_GENESIS_POSITION_UK_NAME_POSITION on GENESIS_POSITION (NAME_POSITION) where DELETE_TS is null ^
-- end GENESIS_POSITION
-- begin GENESIS_DIRECTING
create unique index IDX_GENESIS_DIRECTING_UK_NAME_DIRECTING on GENESIS_DIRECTING (NAME_DIRECTING) where DELETE_TS is null ^
-- end GENESIS_DIRECTING
-- begin GENESIS_DEPARTMENT
create unique index IDX_GENESIS_DEPARTMENT_UK_NAME_DEPARTMENT on GENESIS_DEPARTMENT (NAME_DEPARTMENT) where DELETE_TS is null ^
-- end GENESIS_DEPARTMENT


-- begin GENESIS_TYPE_DOCUMENTS
create unique index IDX_GENESIS_TYPE_DOCUMENTS_UK_NAME_DOCUMENT on GENESIS_TYPE_DOCUMENTS (NAME_DOCUMENT) where DELETE_TS is null ^
-- end GENESIS_TYPE_DOCUMENTS
-- begin GENESIS_EMPLOYEE
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_IMAGE_PHOTO foreign key (IMAGE_PHOTO_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_IMAGE_SIGN foreign key (IMAGE_SIGN_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_DIRECTION_WORK foreign key (DIRECTION_WORK_ID) references GENESIS_DIRECTING(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_PROFESSION foreign key (PROFESSION_ID) references GENESIS_PROFESSIONS(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_NAKS_IMAGE foreign key (NAKS_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_VIK_IMAGE foreign key (VIK_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_VUZ_IMAGE foreign key (VUZ_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_DEPARTMENT foreign key (DEPARTMENT_ID) references GENESIS_DEPARTMENT(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_CK_IMAGE foreign key (UD_CK_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_FIRST_HELP_IMAGE foreign key (UD_FIRST_HELP_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_ECO_SAF_IMAGE foreign key (UD_ECO_SAF_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_WORK_HI_IMAGE foreign key (UD_WORK_HI_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_DRIVE_SAF_IMAGE foreign key (UD_DRIVE_SAF_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_EB_IMAGE foreign key (UD_EB_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_OT_IMAGE foreign key (UD_OT_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_PTM_IMAGE foreign key (UD_PTM_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_UD_PB_IMAGE foreign key (UD_PB_IMAGE_ID) references SYS_FILE(ID)^
create index IDX_GENESIS_EMPLOYEE_IMAGE_PHOTO on GENESIS_EMPLOYEE (IMAGE_PHOTO_ID)^
create index IDX_GENESIS_EMPLOYEE_IMAGE_SIGN on GENESIS_EMPLOYEE (IMAGE_SIGN_ID)^
create index IDX_GENESIS_EMPLOYEE_DIRECTION_WORK on GENESIS_EMPLOYEE (DIRECTION_WORK_ID)^
create index IDX_GENESIS_EMPLOYEE_PROFESSION on GENESIS_EMPLOYEE (PROFESSION_ID)^
create index IDX_GENESIS_EMPLOYEE_NAKS_IMAGE on GENESIS_EMPLOYEE (NAKS_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_VIK_IMAGE on GENESIS_EMPLOYEE (VIK_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_VUZ_IMAGE on GENESIS_EMPLOYEE (VUZ_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_BUILDING on GENESIS_EMPLOYEE (BUILDING_ID)^
create index IDX_GENESIS_EMPLOYEE_DEPARTMENT on GENESIS_EMPLOYEE (DEPARTMENT_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_CK_IMAGE on GENESIS_EMPLOYEE (UD_CK_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_FIRST_HELP_IMAGE on GENESIS_EMPLOYEE (UD_FIRST_HELP_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_ECO_SAF_IMAGE on GENESIS_EMPLOYEE (UD_ECO_SAF_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_WORK_HI_IMAGE on GENESIS_EMPLOYEE (UD_WORK_HI_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_DRIVE_SAF_IMAGE on GENESIS_EMPLOYEE (UD_DRIVE_SAF_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_EB_IMAGE on GENESIS_EMPLOYEE (UD_EB_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_OT_IMAGE on GENESIS_EMPLOYEE (UD_OT_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_PTM_IMAGE on GENESIS_EMPLOYEE (UD_PTM_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_UD_PB_IMAGE on GENESIS_EMPLOYEE (UD_PB_IMAGE_ID)^
-- end GENESIS_EMPLOYEE
-- begin GENESIS_COURSES
alter table GENESIS_COURSES add constraint FK_GENESIS_COURSES_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_COURSES add constraint FK_GENESIS_COURSES_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID)^
create index IDX_GENESIS_COURSES_EMPLOYEE on GENESIS_COURSES (EMPLOYEE_ID)^
create index IDX_GENESIS_COURSES_IMAGE on GENESIS_COURSES (IMAGE_ID)^
-- end GENESIS_COURSES
-- begin GENESIS_STORAGE_FILES
alter table GENESIS_STORAGE_FILES add constraint FK_GENESIS_STORAGE_FILES_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table GENESIS_STORAGE_FILES add constraint FK_GENESIS_STORAGE_FILES_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID)^
create index IDX_GENESIS_STORAGE_FILES_FILE on GENESIS_STORAGE_FILES (FILE_ID)^
create index IDX_GENESIS_STORAGE_FILES_EMPLOYEE on GENESIS_STORAGE_FILES (EMPLOYEE_ID)^
-- end GENESIS_STORAGE_FILES
-- begin GENESIS_BAGS_ENTITY
alter table GENESIS_BAGS_ENTITY add constraint FK_GENESIS_BAGS_ENTITY_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_GENESIS_BAGS_ENTITY_FILE on GENESIS_BAGS_ENTITY (FILE_ID)^
-- end GENESIS_BAGS_ENTITY
-- begin GENESIS_PERSONS
alter table GENESIS_PERSONS add constraint FK_GENESIS_PERSONS_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID)^
create index IDX_GENESIS_PERSONS_BUILDING on GENESIS_PERSONS (BUILDING_ID)^
-- end GENESIS_PERSONS
-- begin GENESIS_BUILDING
alter table GENESIS_BUILDING add constraint FK_GENESIS_BUILDING_IMAGE_CONTRACT foreign key (IMAGE_CONTRACT_ID) references SYS_FILE(ID)^
create index IDX_GENESIS_BUILDING_IMAGE_CONTRACT on GENESIS_BUILDING (IMAGE_CONTRACT_ID)^
-- end GENESIS_BUILDING

-- begin GENESIS_EVENT
alter table GENESIS_EVENT add constraint FK_GENESIS_EVENT_OBJECT foreign key (OBJECT_ID) references GENESIS_BUILDING(ID)^
alter table GENESIS_EVENT add constraint FK_GENESIS_EVENT_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID)^
create index IDX_GENESIS_EVENT_OBJECT on GENESIS_EVENT (OBJECT_ID)^
create index IDX_GENESIS_EVENT_EMPLOYEE on GENESIS_EVENT (EMPLOYEE_ID)^
-- end GENESIS_EVENT

-- begin GENESIS_VACANCIES_REQUEST
alter table GENESIS_VACANCIES_REQUEST add constraint FK_GENESIS_VACANCIES_REQUEST_SPECIALITY foreign key (SPECIALITY_ID) references GENESIS_DIRECTING(ID)^
create index IDX_GENESIS_VACANCIES_REQUEST_SPECIALITY on GENESIS_VACANCIES_REQUEST (SPECIALITY_ID)^
-- end GENESIS_VACANCIES_REQUEST

-- begin GENESIS_REQUEST_ENTITY
alter table GENESIS_REQUEST_ENTITY add constraint FK_GENESIS_REQUEST_ENTITY_SPECIALIST foreign key (SPECIALIST_ID) references GENESIS_DIRECTING(ID)^
alter table GENESIS_REQUEST_ENTITY add constraint FK_GENESIS_REQUEST_ENTITY_PARENT foreign key (PARENT_ID) references GENESIS_REQUEST_ENTITY(ID)^
create index IDX_GENESIS_REQUEST_ENTITY_SPECIALIST on GENESIS_REQUEST_ENTITY (SPECIALIST_ID)^
create index IDX_GENESIS_REQUEST_ENTITY_PARENT on GENESIS_REQUEST_ENTITY (PARENT_ID)^
-- end GENESIS_REQUEST_ENTITY
-- begin GENESIS_REQUEST_ENTITY_COPY
alter table GENESIS_REQUEST_ENTITY_COPY add constraint FK_GENESIS_REQUEST_ENTITY_COPY_SPECIALIST foreign key (SPECIALIST_ID) references GENESIS_DIRECTING(ID)^
alter table GENESIS_REQUEST_ENTITY_COPY add constraint FK_GENESIS_REQUEST_ENTITY_COPY_PARENT foreign key (PARENT_ID) references GENESIS_REQUEST_ENTITY(ID)^
create index IDX_GENESIS_REQUEST_ENTITY_COPY_SPECIALIST on GENESIS_REQUEST_ENTITY_COPY (SPECIALIST_ID)^
create index IDX_GENESIS_REQUEST_ENTITY_COPY_PARENT on GENESIS_REQUEST_ENTITY_COPY (PARENT_ID)^
-- end GENESIS_REQUEST_ENTITY_COPY
-- begin GENESIS_CLAIM_CK
alter table GENESIS_CLAIM_CK add constraint FK_GENESIS_CLAIM_CK_SPECIALTY foreign key (SPECIALTY_ID) references GENESIS_DIRECTING(ID)^
alter table GENESIS_CLAIM_CK add constraint FK_GENESIS_CLAIM_CK_PARENT_CLAIM foreign key (PARENT_CLAIM_ID) references GENESIS_CLAIM_CK(ID)^
alter table GENESIS_CLAIM_CK add constraint FK_GENESIS_CLAIM_CK_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID)^
create index IDX_GENESIS_CLAIM_CK_SPECIALTY on GENESIS_CLAIM_CK (SPECIALTY_ID)^
create index IDX_GENESIS_CLAIM_CK_PARENT_CLAIM on GENESIS_CLAIM_CK (PARENT_CLAIM_ID)^
create index IDX_GENESIS_CLAIM_CK_BUILDING on GENESIS_CLAIM_CK (BUILDING_ID)^
-- end GENESIS_CLAIM_CK
