-- begin GENESIS_PROFESSIONS
create unique index IDX_GENESIS_PROFESSIONS_UK_NAME_PROFESSION on GENESIS_PROFESSIONS (NAME_PROFESSION) where DELETE_TS is null ^
-- end GENESIS_PROFESSIONS
-- begin GENESIS_POSITION
create unique index IDX_GENESIS_POSITION_UK_NAME_POSITION on GENESIS_POSITION (NAME_POSITION) where DELETE_TS is null ^
-- end GENESIS_POSITION
-- begin GENESIS_DIRECTING
create unique index IDX_GENESIS_DIRECTING_UK_NAME_DIRECTING on GENESIS_DIRECTING (NAME_DIRECTING) where DELETE_TS is null ^
-- end GENESIS_DIRECTING
-- begin GENESIS_DEPARTMENT
create unique index IDX_GENESIS_DEPARTMENT_UK_NAME_DEPARTMENT on GENESIS_DEPARTMENT (NAME_DEPARTMENT) where DELETE_TS is null ^
-- end GENESIS_DEPARTMENT

-- begin GENESIS_MY_PHOTO
alter table GENESIS_MY_PHOTO add constraint FK_GENESIS_MY_PHOTO_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_GENESIS_MY_PHOTO_IMAGE on GENESIS_MY_PHOTO (IMAGE_ID)^
-- end GENESIS_MY_PHOTO
-- begin GENESIS_TYPE_DOCUMENTS
create unique index IDX_GENESIS_TYPE_DOCUMENTS_UK_NAME_DOCUMENT on GENESIS_TYPE_DOCUMENTS (NAME_DOCUMENT) where DELETE_TS is null ^
-- end GENESIS_TYPE_DOCUMENTS
-- begin GENESIS_EMPLOYEE
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_POSITION foreign key (POSITION_ID) references GENESIS_POSITION(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_DIRECTION_WORK foreign key (DIRECTION_WORK_ID) references GENESIS_DIRECTING(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_PROFESSION foreign key (PROFESSION_ID) references GENESIS_PROFESSIONS(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_NAKS_IMAGE foreign key (NAKS_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_VIK_IMAGE foreign key (VIK_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_VUZ_IMAGE foreign key (VUZ_IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_EMPLOYEE add constraint FK_GENESIS_EMPLOYEE_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID)^
create index IDX_GENESIS_EMPLOYEE_IMAGE on GENESIS_EMPLOYEE (IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_POSITION on GENESIS_EMPLOYEE (POSITION_ID)^
create index IDX_GENESIS_EMPLOYEE_DIRECTION_WORK on GENESIS_EMPLOYEE (DIRECTION_WORK_ID)^
create index IDX_GENESIS_EMPLOYEE_PROFESSION on GENESIS_EMPLOYEE (PROFESSION_ID)^
create index IDX_GENESIS_EMPLOYEE_NAKS_IMAGE on GENESIS_EMPLOYEE (NAKS_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_VIK_IMAGE on GENESIS_EMPLOYEE (VIK_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_VUZ_IMAGE on GENESIS_EMPLOYEE (VUZ_IMAGE_ID)^
create index IDX_GENESIS_EMPLOYEE_BUILDING on GENESIS_EMPLOYEE (BUILDING_ID)^
-- end GENESIS_EMPLOYEE
-- begin GENESIS_COURSES
alter table GENESIS_COURSES add constraint FK_GENESIS_COURSES_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table GENESIS_COURSES add constraint FK_GENESIS_COURSES_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID)^
create index IDX_GENESIS_COURSES_EMPLOYEE on GENESIS_COURSES (EMPLOYEE_ID)^
create index IDX_GENESIS_COURSES_IMAGE on GENESIS_COURSES (IMAGE_ID)^
-- end GENESIS_COURSES
-- begin GENESIS_STORAGE_FILES
alter table GENESIS_STORAGE_FILES add constraint FK_GENESIS_STORAGE_FILES_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table GENESIS_STORAGE_FILES add constraint FK_GENESIS_STORAGE_FILES_EMPLOYEE foreign key (EMPLOYEE_ID) references GENESIS_EMPLOYEE(ID)^
create index IDX_GENESIS_STORAGE_FILES_FILE on GENESIS_STORAGE_FILES (FILE_ID)^
create index IDX_GENESIS_STORAGE_FILES_EMPLOYEE on GENESIS_STORAGE_FILES (EMPLOYEE_ID)^
-- end GENESIS_STORAGE_FILES
-- begin GENESIS_BAGS_ENTITY
alter table GENESIS_BAGS_ENTITY add constraint FK_GENESIS_BAGS_ENTITY_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_GENESIS_BAGS_ENTITY_FILE on GENESIS_BAGS_ENTITY (FILE_ID)^
-- end GENESIS_BAGS_ENTITY
-- begin GENESIS_PERSONS
alter table GENESIS_PERSONS add constraint FK_GENESIS_PERSONS_BUILDING foreign key (BUILDING_ID) references GENESIS_BUILDING(ID)^
create index IDX_GENESIS_PERSONS_BUILDING on GENESIS_PERSONS (BUILDING_ID)^
-- end GENESIS_PERSONS
-- begin GENESIS_BUILDING
alter table GENESIS_BUILDING add constraint FK_GENESIS_BUILDING_IMAGE_CONTRACT foreign key (IMAGE_CONTRACT_ID) references SYS_FILE(ID)^
create index IDX_GENESIS_BUILDING_IMAGE_CONTRACT on GENESIS_BUILDING (IMAGE_CONTRACT_ID)^
-- end GENESIS_BUILDING
